name: firebase_ml_text_recognition
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # Text recognition
  firebase_ml_vision: ^0.9.7
  http: ^0.12.1
  image_picker: ^0.6.7+11
  image_cropper: 1.4.0
  webview_flutter: ^2.0.8
  fluttertoast: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true